### ISSUE TITLE
Es <code> realmente necesario?

### ISSUE THREAD

**Issue by danielrossyamitrano** [ludica-squamata/AzoeEngineDocSite#1]
Es realmente necesario que las tags `<pre>` y `<code>`  vayan juntas para presentar la estructura de los JSON? Leí por ahi que `<code>` se usa para algo que la máquina pueda reconocer (como un bloque de HTML) y eso no es lo que estamos haciendo. Observé que con `<pre>` solamente las cosas quedan bien igual, y me parece que el _meaning_ del bloque queda mas claro solo con `<pre>`. Te parece si saco las instancias innecesarias de `<code>?`

**Comment by danielrossyamitrano** [comment]
Claro que, los bloques de texto en `<code>` son de hecho cosas que el código lee, asi que en cierto sentido añaden significado, aunque el usuario no vea ninguna diferencia con o sin `<code>`.

**Comment by einacio** [comment]
solo para aclarar:
- &lt;pre> es texto "tal cual": se respetan los espacios y saltos de linea (que de otra manera el html se come)
- &lt;code> es una etiqueta semantica, declaramos que un bloque de texto corresponde a codigo de computadora, a diferencia por ejemplo de &lt;p>, que es un parrafo de texto prosa.

para que &lt;code> se vea como consola, o un editor, basta con algo como:
```
code{
whitespace: pre;  /*respetar espacios*/
font-family:monospace; /*letra de consola*/
background:#f7f7f7; /*para este bonito color gris de fondo*/
}
```
 &lt;pre>&lt;code> indicaria semanticamente que los espacios son relevantes dentro del codigo provisto
